---
name: Base Test
description: This test serves as an example to how a config file may look
base_result_path: "/media/sholto/Datasets/results/20191026"
tests:
- id: Segmentation2dReproj
  est_dataset:
    file_map: "/media/sholto/Datasets/results/ActualResults/nyuv2_results.csv"
    dataset_id: "NYUv2"
  gt_dataset:
    id: "NYUv2"
    zip_file_loc: "/media/sholto/Datasets/datasets/NYUv2/nyu_depth_v2_raw.zip"
    gt_file_loc: "/media/sholto/Datasets/datasets/NYUv2/nyu_depth_v2_labeled.mat"
  label_map:
    csv_path: "/media/sholto/Datasets/results/label_map.csv"
  label_map_dest_col: "nyu40id"
  use_reprojection: False
meta: {}