---
name: Base Test
description: This test serves as an example to how a config file may look
base_result_path: "/media/sholto/Datasets/results/ActualResults/20191008"
tests:
- id: Segmentation3d
  save_path: "../eigen13id/{dataset_id}/{scene_id}/{alg_name}/seg/seg3d"
  est_dataset:
    file_map: "/media/sholto/Datasets/results/ActualResults/scannet_results_conf.csv"
    dataset_id: "SCANNET"
  gt_dataset:
    id: "SCANNET"
    file_map: "/media/sholto/Datasets/datasets/scenenn_val_dataset.csv"
  label_map:
    csv_path: "/media/sholto/Datasets/results/label_map.csv"
  label_map_dest_col: "eigen13id"
  skip_existing: True
meta: {}