---
name: Base Test
description: This test serves as an example to how a config file may look
base_result_path: "/media/sholto/Datasets/results/ActualResults/20191008"
tests:
- id: Segmentation3d
  est_dataset:
    file_map: "/media/sholto/Datasets1/results/ActualResults/scannet_results_conf.csv"
    dataset_id: "SCANNET"
  gt_dataset:
    id: "SCANNET"
    file_map: "/media/sholto/Datasets1/scenenn_val_dataset.csv"
  label_map:
    csv_path: "/media/sholto/Datasets1/results/label_map.csv"
  label_map_dest_col: "nyu40id"
meta: {}