---
name: Base Test
description: This test serves as an example to how a config file may look
base_result_path: "/media/sholto/Datasets/results/ActualResults/20191008"
tests:
- id: SummarizeRes
  dataset_id: SCANNET
  est_dataset:
    file_map: "/media/sholto/Datasets/results/ActualResults/scannet_results_conf.csv"
    dataset_id: "SCANNET"
  label_map:
    csv_path: "/media/sholto/Datasets/results/label_map.csv"
  label_map_dest_col: "eigen13id"
  label_map_dest_name_col: "eigen13class"
meta: {}