---
name: Base Test
description: This test serves as an example to how a config file may look
base_result_path: "/mnt/1C562D12562CEDE8/RESULTS/TestNoDate"
tests:
- id: OdometryAssessment
  gt_dataset:
    id: "SCANNET"
    file_map: "/mnt/1C562D12562CEDE8/DATASETS/csv_conf/scenenn_mock_hd.csv"
  est_dataset:
    file_map: "/mnt/1C562D12562CEDE8/RESULTS/scannet_results_conf.csv"
    label_map: "/mnt/1C562D12562CEDE8/RESULTS/label_map.csv"
    dataset_id: "SCANNET"
meta: {}