---
name: Base Test
description: This test serves as an example to how a config file may look
base_result_path: "/mnt/1C562D12562CEDE8/RESULTS/TestNoDate"
tests:
- id: ExecuteAlg
  alg:
    id: MinkowskiEngine
    weights_path: "/home/sholto/mnt/1C562D12562CEDE8/Repos/Uni/masters/algs/minkowski_runner/weights.pth"
  dataset:
    id: "SCANNET"
    file_map: "/mnt/1C562D12562CEDE8/DATASETS/csv_conf/scenenn_mock_hd.csv"
meta: {}